/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    id("application")
    id("org.springframework.boot") version "4.0.1"
    id("io.spring.dependency-management") version "1.1.7"
    id("org.hibernate.tool.hibernate-tools-gradle") version "7.2.0.Final"
    id("org.springdoc.openapi-gradle-plugin") version "1.9.0"
}


repositories {
    mavenLocal()
    mavenCentral()
}


group = "io.lab"
version = "0.0.1"
description = "Common Modules"
java.sourceCompatibility = JavaVersion.VERSION_21



dependencies {
    // 1. Spring Boot Starters
    implementation("org.springframework.boot:spring-boot-starter")
    testImplementation("org.springframework.boot:spring-boot-starter-test")

    implementation("org.springframework.boot:spring-boot-autoconfigure")
    implementation("org.springframework.boot:spring-boot-test-autoconfigure")

    implementation("org.springframework.boot:spring-boot-starter-webmvc")
    testImplementation("org.springframework.boot:spring-boot-starter-webmvc-test")

    implementation("org.springframework.boot:spring-boot-starter-websocket")

    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    testImplementation("org.springframework.boot:spring-boot-starter-data-jpa-test")

    implementation("org.springframework.boot:spring-boot-starter-jooq")
    testImplementation("org.springframework.boot:spring-boot-starter-jooq-test")

    implementation("org.springframework.boot:spring-boot-starter-security")
    testImplementation("org.springframework.security:spring-security-test")

    implementation("org.springframework.boot:spring-boot-data-redis")

    implementation("org.springframework.boot:spring-boot-starter-validation")
    implementation("org.springframework.boot:spring-boot-jackson2")

    // 2. Third-Party Tools
    implementation("net.datafaker:datafaker:2.5.3")
    implementation("io.jsonwebtoken:jjwt-api:0.13.0")
    runtimeOnly("io.jsonwebtoken:jjwt-jackson:0.13.0")
    runtimeOnly("io.jsonwebtoken:jjwt-impl:0.13.0")

    implementation("org.mapstruct:mapstruct:1.6.3")
    annotationProcessor("org.mapstruct:mapstruct-processor:1.6.3")
    annotationProcessor("org.projectlombok:lombok-mapstruct-binding:0.2.0")

    // 3. Runtime & DB Drivers
    runtimeOnly("org.postgresql:postgresql:42.7.8")
    runtimeOnly("com.h2database:h2")

    // 4. Annotation Processors & Compilation Tools (Order Matters!)
    compileOnly("org.projectlombok:lombok:1.18.42")
    annotationProcessor("org.projectlombok:lombok:1.18.42")

    // Configuration processor moved to annotationProcessor
    annotationProcessor("org.springframework.boot:spring-boot-configuration-processor")

    // Hibernate processor
    compileOnly("org.hibernate.orm:hibernate-processor")
    annotationProcessor("org.hibernate.orm:hibernate-processor")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    developmentOnly("org.springframework.boot:spring-boot-devtools")

    // Doc
    implementation("org.springdoc:springdoc-openapi-starter-webmvc-api:3.0.1")
    implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.1")
}



java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        extendsFrom(configurations.annotationProcessor.get())
    }
}

tasks.withType<Test> {
    useJUnitPlatform()
}
